# Usa una imagen base liviana de Node.js versión 23 con Alpine Linux.
FROM node:23-alpine

# Establece el directorio de trabajo dentro del contenedor.
WORKDIR /var/www/html

# Copia los archivos package.json y package-lock.json (si existe) al contenedor.
COPY package*.json ./

# Instala las dependencias definidas en package.json.
RUN npm install

# Copia el resto de los archivos del proyecto al contenedor.
COPY . .

# Inicia Vite en modo desarrollo.
CMD ["npm", "run", "dev"]